"""Export the trained attention network + preprocessing to TypeScript.

The web app prefers the FastAPI service (which can serve any of the four trained
models). When the service is not configured/reachable it runs THIS exported
attention-v1 network in-process, using the same scaler statistics, weights and
validation-selected thresholds — so the fallback is a real trained model, not a
heuristic. The engine actually used is returned with every prediction.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "lib" / "ml" / "attentionModel.ts"


def _arr(t) -> list:
    return np.asarray(t.detach().cpu().numpy(), dtype=float).round(6).tolist()


def export_attention_to_ts(model, scaler, report: dict, thresholds: dict) -> None:
    sd = model.state_dict()
    payload = {
        "modelVersion": report["productionModelVersion"] if report["productionModel"] == "attention" else "attention-v1",
        "fallbackModelVersion": "attention-v1",
        "featureVersion": report["featureVersion"],
        "datasetVersion": report["datasetVersion"],
        "trainedAt": report["trainedAt"],
        "features": report["features"],
        "targets": report["targets"],
        "scaler": {
            "mean": np.asarray(scaler.mean_, dtype=float).round(6).tolist(),
            "scale": np.asarray(scaler.scale_, dtype=float).round(6).tolist(),
        },
        "thresholds": {t: thresholds[t]["threshold"] for t in report["targets"]},
        "weights": {
            "embedW": _arr(sd["embed_w"]),
            "embedB": _arr(sd["embed_b"]),
            "qW": _arr(sd["q.weight"]), "qB": _arr(sd["q.bias"]),
            "kW": _arr(sd["k.weight"]), "kB": _arr(sd["k.bias"]),
            "vW": _arr(sd["v.weight"]), "vB": _arr(sd["v.bias"]),
            "normW": _arr(sd["norm.weight"]), "normB": _arr(sd["norm.bias"]),
            "h1W": _arr(sd["head.0.weight"]), "h1B": _arr(sd["head.0.bias"]),
            "h2W": _arr(sd["head.3.weight"]), "h2B": _arr(sd["head.3.bias"]),
        },
        "evaluation": {
            k: {"modelVersion": v.get("modelVersion"), "status": v.get("status", "trained"),
                "test": v.get("splits", {}).get("test", {}).get("macro"),
                "perDisorderTest": {
                    d: {m: v["splits"]["test"]["perDisorder"][d][m]
                        for m in ("accuracy", "precision", "recall", "f1", "rocAuc", "threshold", "confusionMatrix")}
                    for d in report["targets"]
                } if v.get("splits") else None,
                "inferenceMsPerSample": v.get("inferenceMsPerSample")}
            for k, v in report["evaluation"].items()
        },
        "dataset": report["dataset"],
        "split": report["split"],
        "productionModel": report["productionModel"],
        "thresholdMethodology": report["thresholdMethodology"],
        "leakage": report["leakage"],
        "featureImportance": report["featureImportance"],
        "limitations": report["limitations"],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// AUTO-GENERATED by ml/export_web.py — do not hand-edit. Run `python3 ml/train.py` to refresh.\n"
        "// Trained attention-v1 weights + validation-selected thresholds + real evaluation results.\n\n"
        f"export const ATTENTION_MODEL = {json.dumps(payload)} as const;\n"
    )
    print(f"exported {OUT.relative_to(ROOT)}")
