// AUTO-GENERATED by ridge-regression training over src/data/students.json (5,200 hybrid samples).
// 80/20 train/test split, seed 42, L2 lambda=1.0. Do not hand-edit: retrain to change.

export type RiskTarget = "dyslexia" | "dysgraphia" | "dyscalculia" | "adhd";

export const MODEL_VERSION = "ridge-v1";

export const MODEL_FEATURES = ["age", "attention", "memory", "reading", "writing", "math", "engagement_min"] as const;

export const FEATURE_MEAN = [10.962885, 71.973288, 75.88275, 70.069346, 67.947038, 73.783788, 18.179808];
export const FEATURE_STD = [3.183426, 14.054835, 13.348972, 14.648203, 14.715122, 15.091928, 7.842176];

export const TRAINING_INFO = {
  "totalSamples": 5200,
  "trainSamples": 4160,
  "testSamples": 1040,
  "algorithm": "Ridge regression (L2=1.0)",
  "split": "80/20, seed 42"
};

export type ModelCard = { intercept: number; weights: number[]; r2: number; mae: number; auc: number | null; highRiskRate: number };

export const RISK_MODELS: Record<RiskTarget, ModelCard> = {
  "dyslexia": {
    "intercept": 27.947402,
    "weights": [
      0.117946,
      -0.058111,
      -0.162235,
      -8.450196,
      -0.19924,
      0.170047,
      -0.083413
    ],
    "r2": 0.575,
    "mae": 6.17,
    "auc": 0.9442,
    "highRiskRate": 0.0327
  },
  "dysgraphia": {
    "intercept": 34.284588,
    "weights": [
      -0.074259,
      -0.060542,
      -0.003703,
      0.146392,
      -9.110524,
      0.34055,
      0.132371
    ],
    "r2": 0.5414,
    "mae": 6.479,
    "auc": 0.891,
    "highRiskRate": 0.0856
  },
  "dyscalculia": {
    "intercept": 22.71732,
    "weights": [
      -0.153624,
      -0.197521,
      0.316873,
      0.097752,
      -0.053464,
      -8.913023,
      -0.037123
    ],
    "r2": 0.5593,
    "mae": 6.23,
    "auc": 0.9258,
    "highRiskRate": 0.0106
  },
  "adhd": {
    "intercept": 36.927726,
    "weights": [
      0.047872,
      -8.700967,
      0.011566,
      0.390009,
      0.146558,
      -0.034718,
      0.121473
    ],
    "r2": 0.5103,
    "mae": 6.422,
    "auc": 0.8604,
    "highRiskRate": 0.1115
  }
};
